nodeLinker: node-modules
packageExtensions:
  "color-button@*":
    peerDependencies:
      "@testing-library/dom": "*"
      "@babel/plugin-transform-react-jsx": "*"
      "@babel/plugin-syntax-flow": "*"
  eslint-config-react-app@*:
    peerDependencies:
      "@babel/plugin-transform-react-jsx": "*"
      "@babel/plugin-syntax-flow": "*"
  react-scripts@*:
    peerDependencies:
      "@babel/plugin-transform-react-jsx": "*"
      "@babel/plugin-syntax-flow": "*"